spring:
  application:
    name: fleet-partner-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fleet-flow
    username: postgres
    password: admin

    # ORM / DATABASE MAPPING
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
